name: rdart_bloc
description: Rdart_Bloc builder if state bloc change.
version: 0.1.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.1

# Add regular dependencies here.
dependencies:
  bloc: ^8.1.2
  rdart:
    path: /Users/adama sogodogo/Documents/rdart

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
